[package]
name = "quantumsub"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Advanced quantum subdomain reconnaissance tool"
license = "GPL-3.0"
repository = "https://github.com/ftprotap9210poc/quantumsub"

# Explicitly declare binary target
[[bin]]
name = "quantumsub"
path = "src/main.rs"  # Path to your main executable

[dependencies]
# Core dependencies
clap = { version = "4.4", features = ["derive", "env"] }
reqwest = { version = "0.11", features = ["blocking", "json", "stream"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.8"

# Networking/Security
openssl = { version = "0.10", features = ["vendored"] }  # Auto-handles OpenSSL on Windows
trust-dns-resolver = "0.23"
sysinfo = "0.30"

# UI/Output
indicatif = "0.17"
console = "0.15"

[dev-dependencies]
tempfile = "3.8"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"  # Smaller binaries
