[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
clap = "2.33"
console = "0.15"
indicatif = "0.16"
rayon = "1.5"
serde_json = "1.0"
trust-dns-resolver = "0.20"
lazy_static = "1.4"
regex = "1.5"
sysinfo = "0.23"
